### ISSUE TITLE
Add OpenSSL backend support

### ISSUE THREAD

**Issue by alilleybrinker** [omnibor/omnibor-rs#185]
Right now we support BoringSSL and RustCrypto as backends in the `gitoid` crate. We should add support for OpenSSL as well, as some packaging ecosystems will likely require that we link with OpenSSL for security certificate purposes. Should be easy enough to do, just need to make a type that implements the `Digest` interface and calls OpenSSL functions under the hood. There's already support for interoperating with OpenSSL in Rust.

**Comment by alilleybrinker** [comment]
Ping @fkautz if you're interested in doing this (no pressure!)

**Comment by fkautz** [comment]
gitoid support was added in #186. It needs to be exposed in omnibor-rs and cli as features.

**Comment by alilleybrinker** [comment]
Going to close this for now in favor of separate issues for bringing it into the `omnibor` crate and the `omnibor-cli` crate along with the other backends.
