### ISSUE TITLE
artifact + debug subcommands panic when given no arguments

### ISSUE THREAD

**Issue by duckinator** [omnibor/omnibor-rs#208]
**Describe the bug**

`omnibor artifact` and `omnibor debug` panic when given now arguments.

However, `omnibor` and `omnibor manifest` do not, implying this may not be deliberate.

**To Reproduce**
1. Run `omnibor artifact` or `omniboar debug` (exactly as specified, no other arguments).

**Expected behavior**
Help text, an error message explaining the issue, or an error message suggesting re-running the command with `--help` for usage information.

**Screenshots**
![image](https://github.com/user-attachments/assets/d4eb035f-2194-49b1-8118-61e14ed69eab)

**Desktop (please complete the following information):**
 - OS: Debian
 - Version: 12

**Additional context**
I see two potential options:
1. show help text like other subcommands (I'm not sure how difficult this would be)
2. replace the `.unwrap()` calls with something like `.expect("For usage information run: omnibor artifact --help")`

**Comment by alilleybrinker** [comment]
Thanks for the report! I've opened #209 with a fix for this; just had to add a `clap` annotation to print help text when no args are provided. Previously this annotation was applied to the top-level CLI type, but not to the types for any of the subcommands. It's now applied consistently to all subcommands.
